[platformio]
default_envs = esp32s3_dev

[env:esp32s3_dev]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DBOARD_HAS_PSRAM

lib_deps =
  bblanchon/ArduinoJson @ ^7
  https://github.com/tzapu/WiFiManager.git
  
[env:esp32s3_prod]
platform = espressif32
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DBOARD_HAS_PSRAM
  -DPROD_BUILD=1

lib_deps =
  bblanchon/ArduinoJson @ ^7
